modify linux prompt display colored error code behavior

diff --git a/linux/bash/bashrc b/linux/bash/bashrc
--- a/linux/bash/bashrc
+++ b/linux/bash/bashrc
@@ -64,9 +64,11 @@ if [ -n "$force_color_prompt" ]; then
 fi
 
 if [ "$color_prompt" = yes ]; then
-#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-#    PS1='\[\033[0;32m\]\[\033[0m\033[0;32m\]\u\[\033[0;32m\]@\[\033[0;32m\]\h \[\033[0;33m\]\w\[\033[0;32m\]$(__git_ps1)\n\[\033[0;32m\]└─▶\[\033[0m\033[0;32m\] \$\[\033[0m\033[0;32m\] \[\033[0m\] '
-    PS1='\[\033[0m\033[01;32m\]\u@\h:\[\033[01;34m\]\w\[\033[01;33m\]$(__git_ps1)\n\[\033[0;32m\]└─▶\[\033[0m\033[0;32m\] \$\[\033[0m\033[0;32m\]\[\033[0m\] '
+  #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+  #PS1='\[\033[0;32m\]\[\033[0m\033[0;32m\]\u\[\033[0;32m\]@\[\033[0;32m\]\h \[\033[0;33m\]\w\[\033[0;32m\]$(__git_ps1)\n\[\033[0;32m\]└─▶\[\033[0m\033[0;32m\] \$\[\033[0m\033[0;32m\] \[\033[0m\] '
+  #PS1='\[\033[0m\033[01;32m\]\u@\h:\[\033[01;34m\]\w\[\033[01;33m\]$(__git_ps1)\n\[\033[0;32m\]└─▶\[\033[0m\033[0;32m\] \$\[\033[0m\033[0;32m\]\[\033[0m\] '
+  #PS1='\[\033[0m\033[01;32m\]\u@\h:\[\033[01;34m\]\w\[\033[01;33m\]$(__git_ps1)\n\[\033[$(if [ $? == 0 ]; then echo "0;32m"; else echo "0;31"; fi)\]└─▶\[\033[0m\033[0;32m\] \$\[\033[0m\033[0;32m\]\[\033[0m\] '
+  PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs
 else
     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
 fi
@@ -80,6 +82,29 @@ xterm*|rxvt*)
 *)
     ;;
 esac
+
+__prompt_command() {
+    local EXIT="$?"             # This needs to be first
+    PS1=""
+
+    local RCol='\[\e[0m\]'
+
+    local Red='\[\e[0;31m\]'
+    local Gre='\[\e[0;32m\]'
+    local BYel='\[\e[1;33m\]'
+    local BBlu='\[\e[1;34m\]'
+    local Pur='\[\e[0;35m\]'
+
+    PS1="${Gre}\u@\h:${BBlu}\w${Gre}$(__git_ps1)\n"
+
+    if [ $EXIT != 0 ]; then
+        PS1+="${Red}└─▶ \$ ${RCol}"      # Add red if exit code non 0
+    else
+        PS1+="${Gre}└─▶ \$ ${RCol}"
+    fi
+
+    #PS1+="${RCol}@${BBlu}\h ${Pur}\W${BYel}$ ${RCol}"
+}
 
 # enable color support of ls and also add handy aliases
 if [ -x /usr/bin/dircolors ]; then
